import Foundation

/// Что из буфера можно записывать в историю.
public enum CapturePolicy {
    /// Предел одной записи в байтах UTF-8. Больше — не сохраняем.
    public static let maxBytes = 256 * 1024

    /// Тип, которым ClipBridge помечает собственные записи в буфер,
    /// чтобы собранный контекст не попадал обратно в историю.
    public static let ownMarkerType = "app.clipbridge.own"

    /// Пометки, которые ставят менеджеры паролей и утилиты (соглашение nspasteboard.org).
    public static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    public enum Reason: Equatable, Sendable {
        case own, concealed, empty, tooLarge
    }

    public enum Decision: Equatable, Sendable {
        case accept(String)
        case reject(Reason)
    }

    /// - Parameters:
    ///   - types: все типы, объявленные в буфере.
    ///   - text: строковое содержимое буфера, если есть.
    public static func evaluate(types: [String], text: String?) -> Decision {
        if types.contains(ownMarkerType) { return .reject(.own) }
        if types.contains(where: skipTypes.contains) { return .reject(.concealed) }
        guard let text, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return .reject(.empty)
        }
        if text.utf8.count > maxBytes { return .reject(.tooLarge) }
        return .accept(text)
    }
}
